#!/bin/bash
CREATE=0
NAME=
while [ $# -ge 1 ]; do
    case $1 in
        --create|-c)	CREATE=1;;
        *)  [ "$NAME" != "" ] && \
            echo "you have already provided name $NAME for the container" \
                >&2 && exit 1
            NAME=$1;;
    esac
    shift
done

[ "$NAME" == "" ] && \
    echo "please provide a name for the container" >&2 && exit 1

if [ $CREATE -eq 1 ]; then
    lxc-create -n "$NAME" -t ubuntu
    cat >> /var/lib/lxc/$NAME/config << EOT
lxc.cgroup.devices.allow = a
lxc.mount.auto = cgroup
lxc.aa_profile = unconfined
EOT
fi

cat >> ./$NAME.install.config << EOT
lxc.include = /var/lib/lxc/$NAME/config
lxc.mount.entry=$PWD/../.. opt/onedock none bind,create=dir 0 0
EOT
COMMANDS="lxc/install-base ubuntu/install-one ubuntu/install-docker \
    ubuntu/install-registry ubuntu/install-onedock \
    lxc/cleanup lxc/lxc-nbd-support"
for CMD in $COMMANDS; do
    lxc-start -d -n $NAME -f $NAME.install.config
    sleep 5s
    lxc-attach -n $NAME -- /opt/onedock/install/$CMD
    lxc-stop -n $NAME
done
lxc-start -d -n $NAME
sleep 10s
lxc-attach -n $NAME -- docker run -d -p 5000:5000 --restart=always \
    --name registry -v /var/lib/docker-registry/data:/var/lib/registry \
    -v /var/lib/docker-registry/certs:/certs \
    -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
    -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key registry:2
rm -f ./$NAME.install.config
exit 0
