#!/bin/bash
cat > /tmp/ubuntu-docker.tmpl << \EOF
NAME="ubuntu"
PATH=docker://rastasheep/ubuntu-sshd
TYPE=OS
DESCRIPTION="Ubuntu Trusty with SSHd"
EOF

# Create the image
oneimage create -d onedock /tmp/ubuntu-docker.tmpl
sleep 2

# Check the image creation status
while oneimage list | grep ubuntu | awk '{if($9 == "lock"){ exit 0 } else { exit 1 }}'
do
    sleep 2
done

# Check that the image is ready (any other state will generate an error)
oneimage list | grep ubuntu | awk '{if($9 == "rdy"){ exit 0 } else { exit 1 }}'

# Check that the image exists in the repository
curl -s -k -X GET https://$HOSTNAME:5000/v2/_catalog | grep image4one
curl -s -k -X GET https://$HOSTNAME:5000/v2/image4one/tags/list | grep 0
