#!/bin/bash
set -e

# Get the docker IP
DOCKER0IP=$(ip addr show dev docker0 | grep 'inet ' | \
    awk '{print $2}' | sed 's/\/.*$//')

# Create test data
cat > /tmp/docker-private.net << EOF
NAME=private
BRIDGE=docker0
NETWORK_ADDRESS="$DOCKER0IP"
NETWORK_MASK= "255.255.0.0"
DNS="$DOCKER0IP"
GATEWAY="$DOCKER0IP"
AR=[TYPE = "IP4", IP = "172.17.10.1", SIZE = "100" ]
VN_MAD=dummy
EOF

# Create private net
onevnet create /tmp/docker-private.net
sleep 2

# Check if the net exists
onevnet show private > /dev/null 2> /dev/null

echo "testing network suceeded"
exit 0
