#!/bin/bash
set -e

onehost create $HOSTNAME -i onedock -v onedock
sleep 2

# Check the host creation status
while onehost list | grep "$HOSTNAME" | \
    awk '{if($7 == "init"){ exit 0 } else { exit 1 }}'
do
    sleep 2
done

# Check that the host has been created sucessfully
onehost list | grep "$HOSTNAME" | \
    awk '{if($13 == "on"){ exit 0 } else { exit 1 }}'

echo "testing host creation suceeded"
exit 0
