#!/bin/bash
source $(dirname $0)/test-common.sh

progress

cat > /tmp/onedock.vm << EOT
NAME = container-img
CPU = 1
MEMORY = 128
DISK = [ IMAGE=ubuntu ]
NIC = [ NETWORK_ID=0 ]
CONTEXT = [ NETWORK = "YES" ]
EOT

create_vm /tmp/onedock.vm

echo "testing first vm creation suceeded"
exit 0
