#!/bin/bash
# Install docker packages
cat > /etc/yum.repos.d/docker.repo << EOT
[dockerrepo]
name=Docker Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/7/
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
EOT
yum install -y docker-engine

systemctl start docker
systemctl enable docker
