#!/bin/bash
docker run -d -p 5000:5000 --restart=always --name registry \
    -v /var/lib/docker-registry/data:/var/lib/registry \
    -v /var/lib/docker-registry/certs:/certs \
    -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
    -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key registry:2
