#!/bin/bash
#
# ONEDock - Docker support for ONE (as VMs)
# Copyright (C) GRyCAP - I3M - UPV
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

DRIVER_PATH=$(dirname $0)
ONEDOCK_FOLDER=$DRIVER_PATH
source ${DRIVER_PATH}/../../onedock.sh
setup_wn
log_onedock_debug "$0 $@"
source ${DRIVER_PATH}/vmmfnc.sh

NAME=$1
VMID=$3

read_xpath "$(onevm show -x $VMID)" \
        "/VM/TEMPLATE/DISK[DATASTORE=\"onedock\"]/PERSISTENT"

PERSISTENT=${XPATH_ELEMENTS[0]}

log_onedock "Reading persistent state"

if [ "$PERSISTENT" == "YES" ]; then

    log_onedock_debug "Found persistent image, saving state"

    read_xpath "$(onevm show -x $VMID)" \
        "/VM/TEMPLATE/DISK[DATASTORE=\"onedock\"]/SOURCE"
    SOURCE=${XPATH_ELEMENTS[0]}
    IMG_NAME=${SOURCE:9}

    log_onedock_debug $(docker commit "$NAME" "$IMG_NAME")
else

    log_onedock_debug "Image is not persistent ($PERSISTENT) so nothing needs to be saved"

fi


ONEDOCK_CONTAINER_FOLDER=${ONEDOCK_FOLDER}/${NAME}
mkdir -p "$ONEDOCK_CONTAINER_FOLDER"
ONEDOCK_CLEANUP_FILE=${ONEDOCK_CONTAINER_FOLDER}/deployment.cleanup

if [ -e "$ONEDOCK_CLEANUP_FILE" ]; then
    exec_file "$ONEDOCK_CLEANUP_FILE" "Failed to cleanup container ($CLEANUP)"
fi

log_onedock_debug $(docker stop "$NAME" && docker rm "$NAME")
ERR=$?

# This is just to clean possible snapshots (maybe there are none)
DISKIMAGENAME=$(build_dock_name "$LOCAL_SERVER" "" "$NAME" "0")
docker rmi "$DISKIMAGENAME" > /dev/null 2> /dev/null

exit 0
