#!/bin/bash
#
# ONEDock - Docker support for ONE (as VMs)
# Copyright (C) GRyCAP - I3M - UPV 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

DRIVER_PATH=$(dirname $0)
source ${DRIVER_PATH}/../../onedock.sh
setup_wn
log_onedock_debug "$0 $@"
source ${DRIVER_PATH}/vmmfnc.sh

domain=$1
mkdir -p `dirname $domain`
cat > $domain
DOMXML=$(cat "$domain")
DATASTOREFOLDER=$(dirname $domain)

ONEDOCK_NETWORK_FILE=$(dirname $domain)/deployment.network
ONEDOCK_DEVICES_FILE=$(dirname $domain)/deployment.devices
ONEDOCK_CONTEXT_FILE=$(dirname $domain)/deployment.context

read_xpath "$DOMXML" "/VM/ID" "/VM/NAME"

unset i

VMID="${XPATH_ELEMENTS[i++]}"
NAME="${XPATH_ELEMENTS[i++]}"
DN=$(readlink -e ${DRIVER_PATH}/../../docker-manage-network)
CONTAINERNAME=one-$VMID
DISKIMAGENAME=$(build_dock_name "$LOCAL_SERVER" "" "$CONTAINERNAME" "0")

ONEDOCK_CONTAINER_FOLDER=${ONEDOCK_FOLDER}/${CONTAINERNAME}
mkdir -p "$ONEDOCK_CONTAINER_FOLDER"
ONEDOCK_CLEANUP_FILE="$ONEDOCK_CONTAINER_FOLDER/deployment.cleanup"
cat > ${ONEDOCK_CLEANUP_FILE} << EOT
EOT
ONEDOCK_BOOTSTRAP_FILE="$ONEDOCK_CONTAINER_FOLDER/deployment.bootstrap"
cat > ${ONEDOCK_BOOTSTRAP_FILE} << EOT
EOT

EXISTS=$(docker inspect -f '{{.State.Running}}' "$CONTAINERNAME" 2>/dev/null)
if [ "$EXISTS" == "false" ] || [ "$EXISTS" == "true" ]; then
    error_message "name $CONTAINERNAME already taken"
    exit -1
fi

DEVICES_STR=$(setup_devices "$DOMXML" "$DATASTOREFOLDER" "$ONEDOCK_DEVICES_FILE" "$ONEDOCK_CLEANUP_FILE" "$ONEDOCK_BOOTSTRAP_FILE")
if [ $? -ne 0 ]; then
    error_message "could not setup devices for deployment $domain"
    exit -1
fi

CONTEXT_STR=$(setup_context "$DOMXML" "$DATASTOREFOLDER" "$ONEDOCK_CONTEXT_FILE" "$ONEDOCK_CLEANUP_FILE" "$ONEDOCK_BOOTSTRAP_FILE")
if [ $? -ne 0 ]; then
    error_message "could not setup context for deployment $domain"
    exit -1
fi

if [ "$DEVICES_STR" != "" -o "$CONTEXT_STR" != "" ]; then
    DEVICES_STR="$DEVICES_STR --cap-add SYS_ADMIN --security-opt apparmor:unconfined"
fi

NETWORK_STR=$(setup_network "$DOMXML" "$DATASTOREFOLDER" "$ONEDOCK_NETWORK_FILE" "$ONEDOCK_CLEANUP_FILE" "$ONEDOCK_BOOTSTRAP_FILE")
if [ $? -ne 0 ]; then
    error_message "could not setup network for deployment $domain"
    exit -1
fi

ONEDOCK_DOCKERRUN=$DATASTOREFOLDER/disk.0.dockerrun
if [ -e "$ONEDOCK_DOCKERRUN" ]; then
    DOCKERRUNCMD="$(cat $ONEDOCK_DOCKERRUN)"
elif [ "$ONEDOCK_DEFAULT_DOCKERRUN" != "" ]; then
    DOCKERRUNCMD="$ONEDOCK_DEFAULT_DOCKERRUN"
else
    DOCKERRUNCMD=
fi
        
log_onedock_debug "docker run $NETWORK_STR $DEVICES_STR $CONTEXT_STR -td --name $CONTAINERNAME $DISKIMAGENAME $DOCKERRUNCMD 2>&1"
data=`docker run $NETWORK_STR $DEVICES_STR $CONTEXT_STR -td --name $CONTAINERNAME $DISKIMAGENAME $DOCKERRUNCMD 2>&1`

if [ $? -eq 0 ]; then
    echo $CONTAINERNAME

    NETCONTEXT="$(
        set -e
        $(cat "$ONEDOCK_NETWORK_FILE")
    )"
    if [ $? -ne 0 ]; then
        docker rm $(docker stop "$CONTAINERNAME")
        # cleanup_disks "$DOMXML" "$DATASTOREFOLDER" "$ONEDOCK_DEVICES_FILE"
        # Here we should clean the loop devices
        exec_file "$ONEDOCK_CLEANUP_FILE"
        error_message "network contextualization failed: $(echo $NETCONTEXT | tr -d '\n')"
        exit 1
    fi
    
    setup_vnc "$DOMXML" "$CONTAINERNAME"
    if [ $? -eq 0 ]; then
        log_onedock_debug "VNC set for $CONTAINERNAME"
    else
        log_onedock_debug "Could not set up VNC for $CONTAINERNAME... has it been defined?"
    fi
    
    exit 0
else
    error_message "Could not create domain from $domain: $data"
    exit -1
fi
