#!/bin/bash
apt install -y xmlstarlet jq git
cd /tmp
git clone -b one5-vagrant https://github.com/indigo-dc/onedock
cd onedock
./setup_files.sh <<< y
cat >> /etc/one/oned.conf << EOT
IM_MAD = [
      NAME          = "onedock",
      SUNSTONE_NAME = "ONEDock",
      EXECUTABLE    = "one_im_ssh",
      ARGUMENTS     = "-r 3 -t 15 onedock" ]
VM_MAD = [
    NAME           = "onedock",
    SUNSTONE_NAME  = "ONEDock",
    EXECUTABLE     = "one_vmm_exec",
    ARGUMENTS      = "-t 15 -r 0 onedock",
    TYPE           = "xml",
    KEEP_SNAPSHOTS = "no",
    IMPORTED_VMS_ACTIONS = "terminate, terminate-hard, hold, release,
        delete, reboot, reboot-hard"
]
TM_MAD_CONF = [
    NAME = "onedock", LN_TARGET = "SELF", CLONE_TARGET = "SELF", SHARED = "YES",
    DS_MIGRATE = "NO"
]
DS_MAD_CONF = [
    NAME = "onedock", REQUIRED_ATTRS = "", PERSISTENT_ONLY = "NO"
]
EOT
sed -i.bak '/^[ \t]*TM_MAD[ \t]*=[ \t]*\[/,/\][ \t]*$/{s/\(ARGUMENTS[ ]*=[ ]*\"[^\"]*\)\(".*$\)/\1,onedock\2/};/^[ \t]*DATASTORE_MAD[ \t]*=[ \t]*\[/,/\][ \t]*$/{s/\(ARGUMENTS[ ]*=[ ]*\"[^\"]*-d [^\"]*\)\( -s [^\"]*\)\(".*$\)/\1,onedock\2,onedock\3/}' /etc/one/oned.conf
echo "Cmnd_Alias ONEDOCK = /var/tmp/one/docker-manage-network,\
    /usr/bin/qemu-nbd, /sbin/losetup, /bin/mount" >> /etc/sudoers.d/opennebula
sed -i.bak 's/^\(oneadmin ALL=.*\)$/\1, ONEDOCK/' /etc/sudoers.d/opennebula
usermod -aG docker oneadmin
sudo service opennebula restart
