#!/bin/bash
apt-get update
apt-get install -y apt-transport-https wget
wget -q -O- http://downloads.opennebula.org/repo/Ubuntu/repo.key \
    | apt-key add -
echo "deb http://downloads.opennebula.org/repo/5.2/Ubuntu/16.04/ \
    stable opennebula" > /etc/apt/sources.list.d/opennebula.list
apt-get -y update
apt-get -y install opennebula opennebula-node
cp /var/lib/one/.ssh/id_rsa.pub /var/lib/one/.ssh/authorized_keys
cat << EOT > /var/lib/one/.ssh/config
Host *
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
EOT
chmod 600 /var/lib/one/.ssh/config /var/lib/one/.ssh/authorized_keys
chown -R oneadmin:oneadmin /var/lib/one/.ssh
