#!/bin/bash
#GPK Key took from: http://docs.docker.com/engine/installation/ubuntulinux/
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 \
    --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
cat << EOT > /etc/apt/sources.list.d/docker.list
# Ubuntu Trusty 14.04 (LTS)
deb https://apt.dockerproject.org/repo ubuntu-xenial main
EOT
apt-get -y update
apt-get -y install linux-image-extra-$(uname -r) docker-engine criu

cat > /etc/init.d/dockerrestart << EOT
#!/bin/bash
cgroups-umount
cgroups-mount
service docker restart
EOT
chmod +x /etc/init.d/dockerrestart
update-rc.d dockerrestart defaults 99
