#!/bin/bash
echo "Onedock installed, creating example image"
sudo service opennebula start
cd /tmp
cat > onedock.ds << EOF
     NAME=onedock
     DS_MAD=onedock
     TM_MAD=onedock
EOF
echo "Creating onedock datastore"
sudo -u oneadmin onedatastore create onedock.ds

cat > ubuntu-docker.tmpl << EOF
     NAME="ubuntu"
     PATH=docker://ubuntu:latest
     TYPE=OS
     DESCRIPTION="Ubuntu"
EOF
echo "Adding example ubuntu image"
sudo -u oneadmin oneimage create -d onedock ubuntu-docker.tmpl

cat > docker-private.net << EOF
     NAME=private
     BRIDGE=docker0
     NETWORK_ADDRESS = "TBC"
     NETWORK_MASK    = "255.255.0.0"
     DNS             = "TBC"
     GATEWAY         = "TBC"
     AR=[TYPE = "IP4", IP = "172.17.10.1", SIZE = "100" ]
     VN_MAD=dummy
EOF

export DOCKER0IP=`/sbin/ifconfig docker0 | grep "inet addr" | awk -F : '{print $2}' | awk '{print $1}'`
sed -i "s/TBC/$DOCKER0IP/g" docker-private.net
echo "Creating onedock network"
sudo -u oneadmin onevnet create docker-private.net

echo "Creating onedock host"
sudo -u oneadmin onehost create $HOSTNAME -i onedock -v onedock
