Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

   config.vm.synced_folder "..", "/onedock"

   config.vm.provision "shell", inline: <<-SHELL
     cd /onedock
     sudo ./install/ubuntu/install-one
     sudo ./install/ubuntu/install-docker
     sudo ./install/ubuntu/install-registry
     sudo ./install/ubuntu/launch-registry
     sudo ./install/ubuntu/install-onedock-one5
     sudo ./install/ubuntu/install-onedock-vagrant-example
     echo "User and Password for oneadmin user:"
     cat /var/lib/one/.one/one_auth
   SHELL

   config.vm.define "one1" do |one1|
     one1.vm.hostname = "one1"
   end

   config.vm.define "one2" do |one2|
     one2.vm.hostname = "one2"
   end


end
