Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
 
   config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get install -y git
     git clone https://github.com/indigo-dc/onedock
     cd onedock
     sudo ./install/install-one
     sudo ./install/install-docker
     sudo ./install/install-registry
     sudo ./install/launch-registry
     sudo ./install/install-onedock
     cat > onedock.ds << EOF
         NAME=onedock
         DS_MAD=onedock
         TM_MAD=onedock
EOF
     onedatastore create onedock.ds

     cat > ubuntu-docker.tmpl << EOF
     NAME="ubuntu"
     PATH=docker://rastasheep/ubuntu-sshd
     TYPE=OS
     DESCRIPTION="Ubuntu Trusty with SSHd"
EOF
     oneimage create -d onedock ubuntu-docker.tmpl

     cat > docker-private.net << EOF
     NAME=private
     BRIDGE=docker0
     NETWORK_ADDRESS = "TBC"
     NETWORK_MASK    = "255.255.0.0"
     DNS             = "TBC"
     GATEWAY         = "TBC"
     AR=[TYPE = "IP4", IP = "172.17.10.1", SIZE = "100" ]
EOF

     export DOCKER0IP=`/sbin/ifconfig docker0 | grep "inet addr" | awk -F : '{print $2}' | awk '{print $1}'`
     sed -i "s/TBC/$DOCKER0IP/g" docker-private.net
     onevnet create docker-private.net

     onehost create $HOSTNAME -i onedock -v onedock -n dummy
     echo "User and Password for oneadmin user:"
     cat /var/lib/one/.one/one_auth
   SHELL
end
