Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

   config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get install -y git
     git clone -b one5-vagrant  https://github.com/indigo-dc/onedock
     cd onedock
     sudo ./install/ubuntu/install-one
     sudo ./install/ubuntu/install-docker
     sudo ./install/ubuntu/install-registry
     sudo ./install/ubuntu/launch-registry
     sudo ./install/ubuntu/install-onedock-one5
     sudo -u oneadmin ./install/ubuntu/install-onedock-vagrant-example
     echo "User and Password for oneadmin user:"
     cat /var/lib/one/.one/one_auth
   SHELL
end
