#!/bin/bash
#
# ONEDock - Docker support for ONE (as VMs)
# Copyright (C) GRyCAP - I3M - UPV 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

DRIVER_PATH=$(dirname $0)
source ${DRIVER_PATH}/../../onedock.sh
log_onedock_debug "$0 $@"
setup_frontend

# -------- Carry out the work ------------

split_dock_name "$SRC" SERVER USER IMAGE TAG

log_onedock "clone is not yet supported"
exit 0

DOCKNAME=$(build_dock_name "$SERVER" "$USER" "$IMAGE" "$TAG")
exec_and_log "docker pull $DOCKNAME" "Error pulling $DOCKNAME"

LOCALDOCKNAME=$(build_dock_name "$LOCAL_SERVER" "" "dockerimage" "$ID")
exec_and_log "docker tag -f $DOCKNAME $LOCALDOCKNAME" \
    "Error creating tag $LOCALDOCKNAME for image $DOCKNAME in local repository"
exec_and_log "docker push $LOCALDOCKNAME" "Error pushing tag $LOCALDOCKNAME"
exec_and_log "docker rmi $DOCKNAME" # 1>&2> /dev/null
log_info "image \"$DOCKNAME\" successfully pushed into \"$LOCALDOCKNAME\""
exit 0
