#!/bin/bash
#
# ONEDock - Docker support for ONE (as VMs)
# Copyright (C) GRyCAP - I3M - UPV 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

DRIVER_PATH=$(dirname $0)
source ${DRIVER_PATH}/../../onedock.sh
log_onedock_debug "$0 $@"
setup_frontend

# stat: returns the size of an image in Mb
# ARGUMENTS: datastore_image_dump image_id
# RETURNS: size
# datastore_image_dump is an XML dump of the driver action encoded in Base 64. See a decoded example.
# size the size of the image in Mb.

DRIVER_ACTION=$1

read_xpath $(echo "$DRIVER_ACTION" |\
    base64 -d) "/DS_DRIVER_ACTION_DATA/IMAGE/PATH"
SRC="${XPATH_ELEMENTS[0]}"

SIZE=0
if [[ "$SRC" =~ ^docker://.*$ ]]; then
    log_onedock_debug "we should check the size from the global\
        docker hub directory"
    SIZE=0
else
    [ ! -f "$SRC" ] && log_error "cannot access to the source file $SRC" &&\
        echo "0" && exit 1
    SIZE=$(tar xfO "$SRC" | wc -c)
    [ $? -ne 0 ] && log_error "could not get the size of file $SRC" &&\
        echo "0" && exit 1
    SIZE=$(( $SIZE / 1048576 ))
fi

echo $SIZE
exit 0



exit 0

# ----------- The following code will check the size from a docker registry v2
#
#source ${DRIVER_PATH}/common-utils
#split_dock_name "$SRC" SERVER USER IMAGE TAG
#XPATH="$XPATH_APP -b $DRV_ACTION"
#
#unset i XPATH_ELEMENTS
#
#while IFS= read -r -d '' element; do
#    XPATH_ELEMENTS[i++]="$element"
#done < <($XPATH     /DS_DRIVER_ACTION_DATA/DATASTORE/TYPE \
#                    /DS_DRIVER_ACTION_DATA/IMAGE/PATH)
#
#unset i
#
#DS_TYPE="${XPATH_ELEMENTS[i++]}"
#SRC="${XPATH_ELEMENTS[i++]}"
#
#SERVER=${SERVER:-$LOCAL_SERVER}
#TAG=${TAG:-latest}
#
#REPOS=https://$SERVER/v2
#SIZE=0
#MANIFEST=$(monitor_and_log "curl -fs -X GET $REPOS/$IMAGE/manifests/$TAG" "Error getting manifest for image $IMAGE")
#if [ $? -ne 0 ]; then
#	echo "error getting image size $IMAGE:$TAG" >&2
#	exit -1
#fi
#
#for blob in $(echo $MANIFEST | jq '.fsLayers[].blobSum' -); do 
#	BLOBID=$(echo $blob | sed 's/^"\(.*\)"$/\1/'i)
#	HEAD=$(curl -sI $REPOS/$IMAGE/blobs/$BLOBID)
#	if [ $? -eq 0 ]; then
#		SHEAD="${HEAD##*Content-Length: }"
#		SHEAD="${SHEAD%%[[:space:]]*}"
#		SIZE=$[ $SIZE + $SHEAD ]
#	else
#		echo "error getting blob $blob" >&2
#	fi
#done
#echo $[ $SIZE / 1048576 ]
