#!/bin/bash
#
# ONEDock - Docker support for ONE (as VMs)
# Copyright (C) GRyCAP - I3M - UPV 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

DRIVER_PATH=$(dirname $0)
source ${DRIVER_PATH}/../../onedock.sh
log_onedock_debug "$0 $@"
setup_frontend

SRC=$1
DST=$2
VMID=$3
DSID=$4

#-------------------------------------------------------------------------------
# Set dst path and dir
#-------------------------------------------------------------------------------
DST_PATH=`arg_path $DST`
DST_HOST=`arg_host $DST`

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

DISK_ID=$(basename ${DST_PATH} | cut -d. -f2)

read_xpath "$(onevm show -x $VMID)" "/VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/IMAGE_ID"

IMAGE_ID="${XPATH_ELEMENTS[0]}"

DOCKER_IMG_NAME=$(build_dock_name "$LOCAL_SERVER" "" "$IMAGE_BASENAME" "$IMAGE_ID")

DOCKER_CMD="docker pull ${DOCKER_IMG_NAME}"
ssh_exec_and_log "$DST_HOST" "$DOCKER_CMD" "Error getting image ${DOCKER_IMG_NAME}"
log_onedock "image ${DOCKER_IMG_NAME} downloaded in $DST_HOST"
exit 0
