#!/bin/bash
echo "Cmnd_Alias ONEDOCK = /var/tmp/one/docker-manage-network,\
    /usr/bin/qemu-nbd, /sbin/losetup, /bin/mount" >> /etc/sudoers.d/opennebula
sed -i.bak-onedock 's/^\(oneadmin ALL=.*\)$/\1, ONEDOCK/' /etc/sudoers.d/opennebula
usermod -aG docker oneadmin
