#!/bin/bash
CREATE=0
NAME=
while [ $# -ge 1 ]; do
	case $1 in
		--create|-c)	CREATE=1;;
		*)		[ "$NAME" != "" ] && echo "you have already provided name $NAME for the container" >&2 && exit 1
				NAME=$1;; 
	esac
	shift
done

[ "$NAME" == "" ] && echo "please provide a name for the container" >&2 && exit 1

if [ $CREATE -eq 1 ]; then
	lxc-create -n "$NAME" -t ubuntu
	cat >> /var/lib/lxc/$NAME/config << EOT
lxc.cgroup.devices.allow = a
lxc.mount.auto = cgroup
lxc.aa_profile = unconfined
EOT
fi

cat >> ./$NAME.install.config << EOT
lxc.include = /var/lib/lxc/$NAME/config
lxc.mount.entry=$PWD opt/setup none bind,create=dir 0 0
EOT
COMMANDS="install-base install-one install-docker install-registry install-onedock cleanup"
for CMD in $COMMANDS; do
	lxc-start -n $NAME -f $NAME.install.config
	sleep 5s
	lxc-attach -n $NAME -- /opt/setup/$CMD
	lxc-stop -n ashlan
done
lxc-start -n ashlan
sleep 5s
lxc-attach -n $NAME -- docker run -d -p 5000:5000 --restart=always --name registry -v /var/lib/docker-registry/data:/var/lib/registry -v /var/lib/docker-registry/certs:/certs -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key registry:2
rm -f ./$NAME.install.config
exit 0
