#!/bin/bash
apt-get install -y xmlstarlet jq git
cd /tmp
git clone https://github.com/indigo-dc/onedock
cd onedock
./setup_files.sh <<< y
cat >> /etc/one/oned.conf << EOT
IM_MAD = [
      name       = "onedock",
      executable = "one_im_ssh",
      arguments  = "-r 3 -t 15 onedock" ]

VM_MAD = [
    name       = "onedock",
    executable = "one_vmm_exec",
    arguments  = "-t 15 -r 0 onedock",
    type       = "xml" ]

TM_MAD_CONF = [
    name = "onedock", ln_target = "SYSTEM", clone_target = "SYSTEM", shared = "yes"
]
EOT
sed -i.bak '/^[ \t]*TM_MAD[ \t]*=[ \t]*\[/,/\][ \t]*$/{s/\(arguments[ ]*=[ ]*\"[^\"]*\)\(".*$\)/\1,onedock\2/};/^[ \t]*DATASTORE_MAD[ \t]*=[ \t]*\[/,/\][ \t]*$/{s/\(arguments[ ]*=[ ]*\"[^\"]*\)\(".*$\)/\1,onedock\2/}' /etc/one/oned.conf
echo "Cmnd_Alias ONEDOCK = /var/tmp/one/docker-manage-network" >> /etc/sudoers.d/opennebula
sed -i.bak 's/^\(oneadmin ALL=.*\)$/\1, ONEDOCK/' /etc/sudoers.d/opennebula
usermod -aG docker oneadmin
sudo service opennebula restart
