#!/bin/bash
rm -rf var_lib_one
rm -rf var_tmp_one
rm -rf etc_one
docker build -t oddevel:frontend ./front-one
docker build -t oddevel:wn ./wn

DOCKID=$(docker run -id oddevel:frontend)
docker cp $DOCKID:/var/lib/one .
mv one var_lib_one
cp -r var_lib_one/remotes ./var_tmp_one
cp var_lib_one/.ssh/id_rsa.pub var_lib_one/.ssh/authorized_keys
cat > var_lib_one/.ssh/config <<\EOT
Host *
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
EOT

docker cp $DOCKID:/etc/one .
mv one etc_one


cat >> ./etc_one/oned.conf << EOT
IM_MAD = [
      name       = "onedock",
      executable = "one_im_ssh",
      arguments  = "-r 3 -t 15 onedock" ]

VM_MAD = [
    name       = "onedock",
    executable = "one_vmm_exec",
    arguments  = "-t 15 -r 0 onedock",
    type       = "xml" ]

TM_MAD_CONF = [
    name = "onedock", ln_target = "SYSTEM", clone_target = "SYSTEM", shared = "yes"
]
EOT
sed -i.bak '/^[ \t]*TM_MAD[ \t]*=[ \t]*\[/,/\][ \t]*$/{s/\(arguments[ ]*=[ ]*\"[^\"]*\)\(".*$\)/\1,onedock\2/};/^[ \t]*DATASTORE_MAD[ \t]*=[ \t]*\[/,/\][ \t]*$/{s/\(arguments[ ]*=[ ]*\"[^\"]*\)\(".*$\)/\1,onedock\2/}' ./etc_one/oned.conf

docker stop $DOCKID && docker rm $DOCKID

cp -r ../datastore/onedock ./var_lib_one/remotes/datastore/
cp -r ../vmm/onedock ./var_lib_one/remotes/vmm/
cp -r ../im/onedock* ./var_lib_one/remotes/im/
cp -r ../tm/onedock ./var_lib_one/remotes/tm/
cp ../onedock.conf ./var_lib_one/remotes/
cp ../onedock.sh ./var_lib_one/remotes/

echo "export LOCAL_SERVER=" >> ./var_lib_one/remotes/onedock.conf
echo "export DATASTORE_DATA_PATH=" >> ./var_lib_one/remotes/onedock.conf

chown -R oneadmin:oneadmin var_lib_one etc_one var_tmp_one

./startfrontend
./startwn wn1