#!/bin/bash
FRONTENDNAME=onedock
IMAGENAME=oddevel:wn

[ $# -ne 1 ] && echo "$0 <node>" && exit 1
WNNAME=$1
docker inspect $WNNAME > /dev/null 2> /dev/null
if [ $? -eq 0 ]; then
    echo "deleting container $WNNAME"
    docker stop $WNNAME
    docker rm $WNNAME
fi

BASEDIR=$(readlink -e $(dirname $0))


docker run --privileged --name $WNNAME -h $WNNAME -v /var/run/docker.sock:/var/run/docker.sock -v $(which docker):/bin/docker -v $BASEDIR/var_lib_one:/var/lib/one -v $BASEDIR/var_tmp_one:/var/tmp/one -id $IMAGENAME /bin/bash
IP=$(docker inspect -f '{{.NetworkSettings.IPAddress}}' $WNNAME)
docker exec $FRONTENDNAME bash -c "cat /etc/hosts | sed \"/$IP/d;/$WNNAME/d\" > /tmp/hosts && echo \"$IP $WNNAME\" >> /tmp/hosts && cp /tmp/hosts /etc/"