#!/bin/bash
ONE_VER=$(dpkg -s opennebula | grep 'Version' | awk '{split($2,onev,"."); print onev[1]}')
set -e

function configure_one4 {
cat >> /etc/one/oned.conf << EOT
#*******************************************************************************
# ONEDOCK configuration
#*******************************************************************************

IM_MAD = [
  name       = "onedock",
  executable = "one_im_ssh",
  arguments  = "-r 3 -t 15 onedock" 
]

VM_MAD = [
  name       = "onedock",
  executable = "one_vmm_exec",
  arguments  = "-t 15 -r 0 onedock",
  type       = "xml" 
]

TM_MAD_CONF = [
  name = "onedock", ln_target = "SYSTEM", clone_target = "SYSTEM", shared = "yes"
]
EOT

  sed -i.bak-onedock '/^[ \t]*TM_MAD[ \t]*=[ \t]*\[/,/\][ \t]*$/{
  s/\(arguments[ ]*=[ ]*\"[^\"]*\)\(".*$\)/\1,onedock\2/};
  /^[ \t]*DATASTORE_MAD[ \t]*=[ \t]*\[/,/\][ \t]*$/{
  s/\(arguments[ ]*=[ ]*\"[^\"]*\)\(".*$\)/\1,onedock\2/}' \
  /etc/one/oned.conf
}

function configure_one5 {
cat >> /etc/one/oned.conf << EOT
#*******************************************************************************
# ONEDOCK configuration
#*******************************************************************************

IM_MAD = [
  NAME          = "onedock",
  SUNSTONE_NAME = "ONEDock",
  EXECUTABLE    = "one_im_ssh",
  ARGUMENTS     = "-r 3 -t 15 onedock" 
]

VM_MAD = [
  NAME           = "onedock",
  SUNSTONE_NAME  = "ONEDock",
  EXECUTABLE     = "one_vmm_exec",
  ARGUMENTS      = "-t 15 -r 0 onedock",
  TYPE           = "xml",
  KEEP_SNAPSHOTS = "no",
  IMPORTED_VMS_ACTIONS = "terminate, terminate-hard, hold, release, delete, reboot, reboot-hard"
]

TM_MAD_CONF = [
  NAME = "onedock", LN_TARGET = "SELF", CLONE_TARGET = "SELF", SHARED = "YES", DS_MIGRATE = "NO"
]

DS_MAD_CONF = [
  NAME = "onedock", REQUIRED_ATTRS = "", PERSISTENT_ONLY = "NO"
]
EOT
  
  sed -i.bak '/^[ \t]*TM_MAD[ \t]*=[ \t]*\[/,/\][ \t]*$/{s/\(ARGUMENTS[ ]*=[ ]*\"[^\"]*\)\(".*$\)/\1,onedock\2/};/^[ \t]*DATASTORE_MAD[ \t]*=[ \t]*\[/,/\][ \t]*$/{s/\(ARGUMENTS[ ]*=[ ]*\"[^\"]*-d [^\"]*\)\( -s [^\"]*\)\(".*$\)/\1,onedock\2,onedock\3/}' /etc/one/oned.conf
}

if [ $ONE_VER -eq 5 ]
then
  configure_one5
else
  configure_one4
fi

sed -i.bkp -e "s/export LOCAL_SERVER=.*/export LOCAL_SERVER=$(hostname):5000/g" /var/lib/one/remotes/onedock.conf
sed -i.bak-onedock 's/^\(oneadmin ALL=.*\)$/\1, ONEDOCK/' /etc/sudoers.d/opennebula
echo "Cmnd_Alias ONEDOCK = /var/tmp/one/docker-manage-network, /usr/bin/qemu-nbd, /sbin/losetup, /bin/mount" >> /etc/sudoers.d/opennebula
usermod -aG docker oneadmin
touch /var/log/onedock.log && chown oneadmin:oneadmin /var/log/onedock.log
chown -R oneadmin:oneadmin /var/lib/one/remotes
